<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>d3d_stress</AssemblyName>
    <RootNamespace>GPU_T.StressTest.Payloads.D3D</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PublishAot Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>

    <PublishSingleFile Condition="!$([MSBuild]::IsOSPlatform('Windows'))">true</PublishSingleFile>
    <SelfContained Condition="!$([MSBuild]::IsOSPlatform('Windows'))">true</SelfContained>
    <EnableCompressionInSingleFile Condition="!$([MSBuild]::IsOSPlatform('Windows'))">true</EnableCompressionInSingleFile>
    <PublishTrimmed Condition="!$([MSBuild]::IsOSPlatform('Windows'))">true</PublishTrimmed>
    <TrimMode Condition="!$([MSBuild]::IsOSPlatform('Windows'))">full</TrimMode>
  </PropertyGroup>

</Project>